language: bash

sudo: required

services:
  - docker

script:
  - docker build -t ecmi/fixml:sim .
  - docker tag -f ecmi/fixml:sim docker.io/ecmi/fixml:sim
  - docker tag -f ecmi/fixml:sim docker.io/ecmi/fixml:latest
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ecmi/fixml:sim
  - docker push ecmi/fixml:latest
