language: bash

sudo: required

services:
  - docker

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t ecmi/fpml:prod .
  - docker tag -f ecmi/fpml:prod docker.io/ecmi/fpml:prod
  - docker push ecmi/fpml:prod
